Models/Ativo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Financeiro.Models
{
    [Table("Ativos")]
    public class Ativo
    {
        [Key]
        [Display(Name = "Código")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Informe o nome do recebimento")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Informe o valor a receber")]
        [Display(Name = "Valor a Pagar")]
        [Range(0, double.MaxValue)]
        public double Valor { get; set; }

        [Required(ErrorMessage = "Informe a data do recebimento")]
        [Display(Name = "Data do Pagamento")]
        public DateTime Data { get; set; }

        [Required(ErrorMessage = "Informe se o recebimento é recorrente")]
        [Display(Name = "Recorrente")]
        public bool Recorrente { get; set; }

        [Display(Name = "Quantidade de Parcelas")]
        public int Parcelas { get; set; } = 1;

        public int PessoaId { get; set; }

        public Pessoa Pessoa { get; set; }
    }
}

Models/Categoria.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Financeiro.Models
{
    [Table("Categorias")]
    public class Categoria
    {
        public Categoria()
        {
            Passivos = new List<Passivo>();
        }

        [Key]
        [Display(Name = "Código")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Informe o nome do recebimento")]
        public string Nome { get; set; }

        public List<Passivo> Passivos { get; }
    }
}

Models/Passivo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Financeiro.Models
{
    [Table("Passivos")]
    public class Passivo
    {
        [Key]
        [Display(Name = "Código")]
        public int Id { get; set; }

        [Required]
        public string Nome { get; set; }

        [Required]
        [Display(Name = "Valor Recebido")]
        public double Valor { get; set; }

        [Required]
        [Display(Name = "Data de Recebimento")]
        public DateTime Data { get; set; }

        [Required]
        public bool Recorrente { get; set; }

        [Required]
        [Display(Name = "Quantidade de Parcelas")]
        public int Parcelas { get; set; }

        public int PessoaId { get; set; }

        public Pessoa Pessoa { get; set; }

        public int CategoriaId { get; set; }

        public Categoria Categoria { get; }
    }
}

Models/Pessoa.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Financeiro.Models
{
    [Table("Pessoas")]
    public class Pessoa
    {
        public Pessoa()
        {
            Salarios = new List<Salario>();
            Ativos = new List<Ativo>(); ;
            Passivos = new List<Passivo>();
        }

        [Key]
        [Display(Name = "Código")]
        public int Id { get; set; }

        [Required]
        public string Nome { get; set; }

        public List<Salario> Salarios { get; }

        public List<Ativo> Ativos { get; }

        public List<Passivo> Passivos { get; }

    }
}

Models/Salario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Financeiro.Models
{
    [Table("Salarios")]
    public class Salario
    {
        [Key]
        [Display(Name = "Código")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Informe um Sálario")]
        public double Valor { get; set; }

        [Required(ErrorMessage = "Informe o dia do pagamento")]
        [Display(Name = "Dia do Pagamento")]
        public int DiaPagamento { get; set; }

        public int PessoaId { get; set; }

        public Pessoa Pessoa { get; set; }

        public int SalarioCategoriaId { get; set; }

        public SalarioCategoria SalarioCategoria { get; set; }

    }
}

Models/SalarioCategoria.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Financeiro.Models
{
    [Table("SalarioCatetorias")]
    public class SalarioCategoria
    {
        public SalarioCategoria()
        {
               Salarios = new List<Salario>();
        }

        [Key]
        [Display(Name = "Código")]
        public int Id { get; set; }

        public string Nome { get; set; }

        public List<Salario> Salarios { get; }
    }
}

Controllers/HomeController.cs
using Financeiro.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Financeiro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/PessoaController.cs
using Financeiro.Interfaces;
using Financeiro.Models;
using Microsoft.AspNetCore.Mvc;

namespace Financeiro.Controllers
{
    public class PessoaController : Controller
    {
        private readonly IPessoaRepository _pessoaRepository;

        public PessoaController(IPessoaRepository pessoaRepository)
        {
            _pessoaRepository = pessoaRepository;
        }

        public IActionResult Index()
        {
            var pessoas = _pessoaRepository.CarregarPessoas;
            return View(pessoas);
        }

        [HttpGet]
        public IActionResult Editar()
        {
            return View(new Pessoa());
        }

        [HttpPost]
        public IActionResult Editar(Pessoa pessoa)
        {
            if (pessoa is null)
                throw new ArgumentNullException(nameof(pessoa));

            if (ModelState.IsValid)
                _pessoaRepository.SalvarPessoa(pessoa);

            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Pessoa/Editar.cshtml
@model Financeiro.Models.Pessoa

@{
    ViewData["Title"] = "Editar";
}

<div class="row">
    <div class="col-12">
        @if (Model.Id == 0)
        {
            <h1>Cadastar Pessoa</h1>
        }
        else
        {
            <h1>Editar Pessoa</h1>
        }
    </div>
    <div class="col-md-6">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label mb-1"></label>
                <input asp-for="Nome" class="form-control mb-3" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-danger" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
    <div class="col-6">
        <img src="~/images/editar.jpg" width="100%" class="img-fluid" alt="Moça cabelo cacheado">
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pessoa/Index.cshtml
@model IEnumerable<Pessoa>

@{
    ViewData["Title"] = "Pessoas";
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Cadastro de Pessoas</h1>
        </div>
        <div class="col-md-6">
            <table class="table table-bordered mt-4">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nome</th>
                        <th>Detalhes</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var pessoa in Model)
                    {
                        <tr>
                            <td>@pessoa.Id</td>
                            <td>@pessoa.Nome</td>
                            <td>
                                <a href="#" class="btn btn-primary btn-sm">Detalhes</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="text-center mt-12">
                <a href="@Url.Action("Editar", "Pessoa")" class="btn btn-success">Adicionar Nova Pessoa</a>
            </div>
        </div>
        <div class="col-6">
            <img src="~/images/pessoas.jpg" width="80%" class="img-fluid" alt="Casal se cumprimentando">
        </div>
        <div class="col-md-4 image-container"></div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Financeiro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Financeiro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Financeiro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Pessoas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>